//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTourService_991531576
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourInfo
    {
        public int TourId { get; set; }
        public string Destination { get; set; }
    }
}
